RailwaySystem/RailwaySystem/Models/ErrorViewModel.cs
namespace RailwaySystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RailwaySystem/RailwaySystem/Models/MainDBContext.cs
using Microsoft.EntityFrameworkCore;

namespace RailwaySystem.Models
{
    public class MainDBContext : DbContext
    {
        public MainDBContext(DbContextOptions options):base(options) { }
        public DbSet<Railway> Railways { get; set; }
    }
}

RailwaySystem/RailwaySystem/Models/Railway.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace RailwaySystem.Models
{
    public class Railway
    {
        [Key]
        public int TrainId { get; set; }

        public int TrainNo { get; set; }

        [Required(ErrorMessage ="This Field is required")]
        [DisplayName("Train Name")]
        public string TrainName { get; set; }
        public DateTime Schedule { get;set; }

        [Required(ErrorMessage ="This field is required")]
        [DisplayName("Train Source")]
        public string Source { get; set; }

        [Required(ErrorMessage ="This field is required")]
        [DisplayName("Train Destination")]
        public string Destination { get;set; }
    }
}

RailwaySystem/RailwaySystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RailwaySystem.Models;
using System.Diagnostics;

namespace RailwaySystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RailwaySystem/RailwaySystem/Controllers/RailwaysController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RailwaySystem.Models;
using System.Reflection.Metadata.Ecma335;
using System.Text.Json.Serialization;

namespace RailwaySystem.Controllers
{
    public class RailwaysController : Controller
    {
        private readonly MainDBContext _dbContext;
        public RailwaysController(MainDBContext dbContext)
        {
            _dbContext = dbContext;
        }
        public async Task<IActionResult> Index()
        {
            var rail = _dbContext.Railways;
            return View(await rail.ToListAsync());
        }
        public async Task<IActionResult>AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                return View(new Railway());
            }
            else
            {
                var details = await _dbContext.Railways.FirstOrDefaultAsync(x => x.TrainId == id);
                if (details == null)
                {
                    return NotFound();
                }
                return View(details);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [NoDirectAccess]
        public async Task<IActionResult>AddOrEdit(int id, [Bind("TrainId,TrainNo,TrainName,Schedule,Source,Destination")]Railway railway)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {

                    _dbContext.Add(railway);
                    await _dbContext.SaveChangesAsync();
                }
                else
                {
                    try
                    {
                        _dbContext.Update(railway);
                        await _dbContext.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!TrainExist(railway.TrainId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return Json(new { isValid = true, html = Helper.viewtostring(this, "_ViewAll", _dbContext.Railways.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.viewtostring(this, "AddOrEdit", railway) });
        }

        private bool TrainExist(int trainId)
        {
            throw new NotImplementedException();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var rail = await _dbContext.Railways.FindAsync(id);
            _dbContext.Railways.Remove(rail);
            await _dbContext.SaveChangesAsync();
            return Json(new { html = Helper.viewtostring(this, "_ViewAll", _dbContext.Railways.ToList()) });
        }
    }
}

RailwaySystem/RailwaySystem/Views/Railways/AddOrEdit.cshtml
@model RailwaySystem.Models.Railway

<div class="row">
    <div class="col-md-10">
        <form asp-action="AddOrEdit" asp-route-id="@Model.TrainId" onsubmit="return jQueryAjaxPost(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TrainId" />
            <div class="form-group">
                <label asp-for="TrainNo" class="control-label"></label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">#</div>
                    </div>
                    <input asp-for="TrainNo" class="form-control" />
                </div>
                <span asp-validation-for="TrainNo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TrainName" class="control-label"></label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">#</div>
                    </div>
                    <input asp-for="TrainName" class="form-control" />
                </div>
                <span asp-validation-for="TrainName" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Schedule" class="control-label"></label>
                        <input asp-for="Schedule" class="form-control" />
                        <span asp-validation-for="Schedule" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Source" class="control-label"></label>
                        <input asp-for="Source" class="form-control" />
                        <span asp-validation-for="Source" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Destination" class="control-label"></label>
                        <input asp-for="Destination" class="form-control" />
                        <span asp-validation-for="Destination" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10 offset-md-3">
                    <input type="submit" value="Submit" class="btn btn-primary btn-block" />
                </div>
            </div>
        </form>
    </div>
</div>

RailwaySystem/RailwaySystem/Views/Railways/Index.cshtml
@model IEnumerable<RailwaySystem.Models.Railway>

@{
    ViewData["Title"] = "Index";
}

<div id="view-all">
    @await Html.PartialAsync("_ViewAll",Model)
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

RailwaySystem/RailwaySystem/Views/Railways/_ViewAll.cshtml
@model IEnumerable<RailwaySystem.Models.Railway>

<h1 class="text-center"><i class=" text-success"></i> Railway List</h1>
<table class="table">
    <thead class="thead-light">
        <tr>
            <th>@Html.DisplayNameFor(model=>model.TrainNo)</th>


            <th>@Html.DisplayNameFor(model=>model.TrainName)</th>


            <th>@Html.DisplayNameFor(model=>model.Schedule)</th>


            <th>@Html.DisplayNameFor(model=>model.Source)</th>
            <th>@Html.DisplayNameFor(model=>model.Destination)</th>

            <th>
                <a onclick="showInPopup('@Url.Action("AddOrEdit","Railways",null,Context.Request.Scheme)','New Employee')" class="btn btn-success text-white"><i class="fas fa-random"></i> New Train</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(model=>item.TrainNo)</td>

                <td>@Html.DisplayFor(model=>item.TrainName)</td>

                <td>@Html.DisplayFor(model=>item.Schedule)</td>

                <td>@Html.DisplayFor(model=>item.Source)</td>
                <td>@Html.DisplayFor(model=>item.Destination)</td>


                <td>
                    <div>
                        <a onclick="showInPopup('@Url.Action("AddOrEdit","Railways",new {id=item.TrainId},Context.Request.Scheme)','Update Transaction')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i> Edit</a>
                        <form asp-action="Delete" asp-route-id="@item.TrainId" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        </form>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

RailwaySystem/RailwaySystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RailwaySystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RailwaySystem.styles.css" asp-append-version="true" />
    <link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" data-rocket-async="style" as="style" onload="this.onload=null;this.rel='stylesheet'" onerror="this.removeAttribute('data-rocket-async')" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RailwaySystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="modal" tabindex="-1" role="dialog" id="form-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>

    <div class="loaderbody" id="loaderbody">
        <div class="loader"></div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RailwaySystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>