OneToMany1/OneToMany1/Models/Department.cs
using System.ComponentModel.DataAnnotations;

namespace OneToMany1.Models
{
    public class Department
    {
        [Key]
        public int DepId { get;set; }
        public string DepName { get;set; }
        public IList<Employee> Employees { get; set; }
    }
}

OneToMany1/OneToMany1/Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace OneToMany1.Models
{
    public class Employee
    {
        [Key]
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string Location { get; set; }
        public DateTime DateOfJoining { get; set; }
        public string Gender { get; set; }
        public string State { get;set; }
        public string Country { get;set; }
        public int PostalCode { get;set; }
        public string Education { get;set; }

        public Department Department { get; set; }
        public int DepId { get;set; }
    }
}

OneToMany1/OneToMany1/Models/ErrorViewModel.cs
namespace OneToMany1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OneToMany1/OneToMany1/Models/MainDBContext.cs
using Microsoft.EntityFrameworkCore;

namespace OneToMany1.Models
{
    public class MainDBContext : DbContext
    {
        public MainDBContext(DbContextOptions options):base(options) { }

        public DbSet <Employee> Employees { get; set; } 
        public DbSet<Department> Departments { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Employee>()
                .HasOne<Department>(d => d.Department)
                .WithMany(d => d.Employees)
                .HasForeignKey(d => d.DepId)
                .OnDelete(DeleteBehavior.Cascade);
        }
    }
}

OneToMany1/OneToMany1/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OneToMany1.Models;

namespace OneToMany1.Controllers
{
    public class DepartmentsController : Controller
    {
      private readonly MainDBContext _dbContext;
        public DepartmentsController(MainDBContext dbContext)
        {
            _dbContext = dbContext;
        }   
        public async Task<IActionResult> Index()
        {
            var dep = await _dbContext.Departments.ToListAsync();
            return View(dep);   
        }
        public async Task<IActionResult>AddOrEdit(int id = 0)
        {
            if(id == 0)
            {
                return View(new Department());
            }
            else
            {
                var dep = await _dbContext.Departments.FindAsync(id);
                if(dep == null)
                {
                    return NotFound();
                }
                return View(dep);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>AddOrEdit(int id,Department department)
        {
            if (id == 0)
            {
                _dbContext.Departments.Add(department);
                await _dbContext.SaveChangesAsync();
            }
            else
            {
                try
                {
                    _dbContext.Departments.Update(department);
                    await _dbContext.SaveChangesAsync();
                }
                catch
                {
                    if (!Department(department.DepId))
                    {
                        return NotFound();
                    }
                    else
                        throw;
                }
                return Json(new { isValid = true, html = Helper.viewtostring(this, "ViewAll", _dbContext.Departments.ToListAsync()) });
            }
            return Json(new { isValid = false, html = Helper.viewtostring(this, "AddOrEdit", department) });
        }

        private bool Department(int depId)
        {
            throw new NotImplementedException();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Delete(int id)
        {
            var dep = await _dbContext.Departments.FindAsync(id);
            _dbContext.Departments.Remove(dep);
            await _dbContext.SaveChangesAsync();
            return Json(new { html = Helper.viewtostring(this, "ViewAll") });
        }
    }
}

OneToMany1/OneToMany1/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OneToMany1.Models;

namespace OneToMany1.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly MainDBContext _dbContext;
        public EmployeesController(MainDBContext dbContext)
        {
            _dbContext = dbContext;
        }
        public async Task<IActionResult> Index()
        {
            var emp = _dbContext.Employees.Include(d => d.Department);
            return View(await emp.ToListAsync());   
        }
        public async Task<IActionResult>AddOrEdit(int id = 0)
        {
            if(id == 0)
            {
                ViewData["DepId"] = new SelectList(_dbContext.Departments, "DepId", "DepName");
                return View(new Employee());
            }
            else
            {
                var emp = await _dbContext.Employees.FindAsync(id);
                if (emp == null)
                {
                    return NotFound();
                }
                ViewData["DepId"] = new SelectList(_dbContext.Departments, "DepId", "DepName");
                return View(emp);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>AddOrEdit(int id, [Bind("EmpId,EmpName,Location,DateOfJoining,Gender,State,Country,PostalCode,Education,DepId")]Employee employee)
        {
            if (id == 0)
            {
                ViewData["DepId"] = new SelectList(_dbContext.Departments, "DepId", "DepName");
                _dbContext.Employees.Add(employee);
                await _dbContext.SaveChangesAsync();
            }
            else
            {
                try
                {
                    _dbContext.Employees.Update(employee);
                    await _dbContext.SaveChangesAsync();
                }
                catch
                {
                    if (!Employee(employee.EmpId))
                    {
                        ViewData["DepId"] = new SelectList(_dbContext.Departments, "DepId", "DepName");
                        return NotFound();
                    }
                    else
                        throw;
                }
                return Json(new { isValid = true, html = Helper.viewtostring(this, "ViewAll", _dbContext.Employees.ToListAsync()) });
            }
            return Json(new { isValid = false, html = Helper.viewtostring(this, "AddOrEdit", employee) });
        }

        private bool Employee(int empId)
        {
            throw new NotImplementedException();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Delete(int id)
        {
            var emp = await _dbContext.Employees.FindAsync(id);
            _dbContext.Employees.Remove(emp);
            await _dbContext.SaveChangesAsync();
            return Json(new { html = Helper.viewtostring(this, "ViewAll") });
        }
    }
}

OneToMany1/OneToMany1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OneToMany1.Models;
using System.Diagnostics;

namespace OneToMany1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OneToMany1/OneToMany1/Views/Departments/AddOrEdit.cshtml
@model OneToMany1.Models.Department
@{
    Layout = null;
}
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.DepId" onsubmit="return jQueryAjaxPost(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DepId" />

            <div class="form-group">
                <label asp-for="DepName" class="control-label"></label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">#</div>
                    </div>
                    <input asp-for="DepName" class="form-control" />
                </div>
                <span asp-validation-for="DepName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="col-md-6 offset-md-3">
                    <input type="submit" value="Submit" class="btn btn-primary btn-block" />
                </div>
            </div>
        </form>
    </div>
</div>

OneToMany1/OneToMany1/Views/Departments/Index.cshtml
@model IEnumerable<OneToMany1.Models.Department>
@{
    ViewData["Title"] = "Index";
}

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

OneToMany1/OneToMany1/Views/Departments/_ViewAll.cshtml
@model IEnumerable<OneToMany1.Models.Department>
<h1 class="text-center"><i class=" text-success"></i> Department</h1>
<table class="table">
    <thead class="thead-light">
        <tr>

            <th>@Html.DisplayNameFor(model=>model.DepName)</th>
            <th>
                <a onclick="showInPopup('@Url.Action("AddOrEdit","Departments",null,Context.Request.Scheme)','New Department')" class="btn btn-success text-white"><i class="fas fa-random"></i>New Department</a>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>@Html.DisplayFor(model=>item.DepName)</td>
                <td>
                    <a onclick="showInPopup('@Url.Action("AddOrEdit","Departments",new {id=item.DepId},Context.Request.Scheme)','Update Department')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i> Edit</a>
                    <form asp-action="Delete" asp-route-id="@item.DepId" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                    </form>
                </td>

            </tr>
        }
    </tbody>
</table>

OneToMany1/OneToMany1/Views/Employees/AddOrEdit.cshtml
@model OneToMany1.Models.Employee
@{
    Layout = null;
}
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.EmpId" onsubmit="return jQueryAjaxPost(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EmpId" />
            

            <div class="form-group">
                <label asp-for="EmpName" class="control-label"></label>
                <div class="input-group">
                    <div class="input-group-prepend">
                    </div>
                    <input asp-for="EmpName" class="form-control" />
                </div>
                <span asp-validation-for="EmpName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfJoining" class="control-label"></label>
                <input asp-for="DateOfJoining" class="form-control" />
                <span asp-validation-for="DateOfJoining" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Education" class="control-label"></label>
                <input asp-for="Education" class="form-control" />
                <span asp-validation-for="Education" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepId" class="Control-label">Dep Name</label>
                <select asp-for="DepId" asp-items="ViewBag.DepId" class="form-control"></select>
            </div>
            <div class="form-group">
                <div class="col-md-6 offset-md-3">
                    <input type="submit" value="Submit" class="btn btn-primary btn-block" />
                </div>
            </div>

          
        </form>
    </div>
</div>

OneToMany1/OneToMany1/Views/Employees/Index.cshtml
@model IEnumerable<OneToMany1.Models.Employee>

@{
    ViewData["Title"] = "Index";
}

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

OneToMany1/OneToMany1/Views/Employees/_ViewAll.cshtml
@model IEnumerable<OneToMany1.Models.Employee>

    <h1 class="text-center">Employee List</h1>
    <table class="table">
        <thead>
            <tr>
            <th>@Html.DisplayNameFor(model=>model.EmpId)</th>

            <th>@Html.DisplayNameFor(model=>model.EmpName)</th>
            <th>@Html.DisplayNameFor(model=>model.Location)</th>
            <th>@Html.DisplayNameFor(model=>model.DateOfJoining)</th>
            <th>@Html.DisplayNameFor(model=>model.Gender)</th>
            <th>@Html.DisplayNameFor(model=>model.State)</th>
            <th>@Html.DisplayNameFor(model=>model.Country)</th>
            <th>@Html.DisplayNameFor(model=>model.PostalCode)</th>
            <th>@Html.DisplayNameFor(model=>model.Education)</th>
            <th>@Html.DisplayNameFor(model=>model.Department.DepName)</th>
            <a onclick="showInPopup('@Url.Action("AddOrEdit","Employees",null,Context.Request.Scheme)','New Employee')" class="btn btn-success text-white"><i class="fas fa-random"></i>New Employee</a>


            </tr>
        </thead>
        <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayNameFor(model=>model.EmpId)</td>

                <td>@Html.DisplayNameFor(model=>model.EmpName)</td>
                <td>@Html.DisplayNameFor(model=>model.Location)</td>
                <td>@Html.DisplayNameFor(model=>model.DateOfJoining)</td>
                <td>@Html.DisplayNameFor(model=>model.Gender)</td>
                <td>@Html.DisplayNameFor(model=>model.State)</td>
                <td>@Html.DisplayNameFor(model=>model.Country)</td>
                <td>@Html.DisplayNameFor(model=>model.PostalCode)</td>
                <td>@Html.DisplayNameFor(model=>model.Education)</td>
                <td>@Html.DisplayNameFor(model=>model.Department.DepName)</td>
                <a onclick="showInPopup('@Url.Action("AddOrEdit","Employees",new {id=item.EmpId},Context.Request.Scheme)','Update Enployee')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i> Edit</a>
                <form asp-action="Delete" asp-route-id="@item.EmpId" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                    <input type="submit" value="Delete" class="btn btn-danger">
                </form>
            </tr>
        }
        </tbody>
    </table>